### ISSUE TITLE
"프로젝트에 자동 추가" 워크플로우 생성

### ISSUE THREAD

**Issue by seokjeatuiti** [uitiorg/.github#1]
하나의 주제와 연관된 이슈와 PR들의 관계성을 설명이나, 링크, sub-issue 형태로 태깅해서 올려주시고 계시는데요,
리뷰할 때 특정 주제와 연관된 N개 이상의 작업들의 진행 상황을 파악하기가 다소 어려운 실정입니다.
ORG에는 project라는 칸반보드를 제공하고 있는데요, 이슈나 PR 생성 시 여기에 자동으로 등록할 수 있도록 하는 기능이 있는데
이걸 활용하면 간극을 약간 해소할 수 있을 것으로 기대됩니다. 검토 부탁드립니다! 🙏 

```yml
name: Auto Add to Org Project

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  add_to_project:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      projects: write
    steps:
      - name: Add to Organization Project
        uses: actions/add-to-project@v1
        with:
          project-url: https://github.com/orgs/YOUR_ORGANIZATION/projects/YOUR_PROJECT_NUMBER
          github-token: ${{ secrets.GITHUB_TOKEN }}
          item-id: ${{ github.event.issue.node_id || github.event.pull_request.node_id }}
          item-type: ${{ github.event_name == 'issues' && 'issue' || 'pull_request' }}
```

이슈/PR 최초 등록 시 TODO로 등록되고, 종료 시 DONE으로 상태가 자동 변경됩니다.
![Image](https://github.com/user-attachments/assets/e0a083a8-739e-4220-8315-dc9d2ce1993c)

기존 프로젝트:
https://github.com/orgs/uitiorg/projects/2/views/1
